### ISSUE TITLE
Starting client app when photon is unavailable causes undesirable failures

### ISSUE THREAD

**Issue by bobjana** [muoncore/newton#51]
Should try to obtain global locks in background & load stream indexes only when photon is available

```
7-06 08:09:08.748  INFO 25446 --- [service/Profile] i.m.newton.cluster.LocalOnlyLockService  : Global lock 'ProfileView-core-service/Profile' released! Will try again in 500ms
2017-07-06 08:09:08.748  INFO 25446 --- [queEmailService] i.m.newton.cluster.LocalOnlyLockService  : Global lock 'ProfileUniqueEmailService' released! Will try again in 500ms
2017-07-06 08:09:08.748  INFO 25446 --- [-service/Device] i.m.newton.cluster.LocalOnlyLockService  : Global lock 'OrganizationUnitView-core-service/Device' released! Will try again in 500ms
2017-07-06 08:09:08.962  INFO 25446 --- [-service/Device] i.m.newton.cluster.LocalOnlyLockService  : Waiting on the lock DeviceLookupService-core-service/Device
2017-07-06 08:09:08.962  INFO 25446 --- [-service/Device] i.m.newton.cluster.LocalOnlyLockService  : Obtained global lock 'DeviceLookupService-core-service/Device', executing local task on this node
2017-07-06 08:09:08.963  WARN 25446 --- [-service/Device] i.m.newton.cluster.LocalOnlyLockService  : Locked process has failed with an exception, and DeviceLookupService-core-service/Device has been unlocked
2017-07-06 08:09:08.963  WARN 25446 --- [-service/Device] i.m.newton.cluster.LocalOnlyLockService  : Locking Process failed with exception

java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:70)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:82)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getReadConnectionSource(ClusterBinding.java:63)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:402)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:510)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:81)
	at com.mongodb.Mongo.execute(Mongo.java:836)
	at com.mongodb.Mongo$2.execute(Mongo.java:823)
	at com.mongodb.DBCursor.initializeCursor(DBCursor.java:870)
	at com.mongodb.DBCursor.hasNext(DBCursor.java:142)
	at com.mongodb.DBCursor.one(DBCursor.java:679)
	at com.mongodb.DBCollection.findOne(DBCollection.java:833)
	at com.mongodb.DBCollection.findOne(DBCollection.java:796)
	at com.mongodb.DBCollection.findOne(DBCollection.java:743)
	at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2185)
	at org.springframework.data.mongodb.core.MongoTemplate$FindOneCallback.doInCollection(MongoTemplate.java:2169)
	at org.springframework.data.mongodb.core.MongoTemplate.executeFindOneInternal(MongoTemplate.java:1921)
	at org.springframework.data.mongodb.core.MongoTemplate.doFindOne(MongoTemplate.java:1732)
	at org.springframework.data.mongodb.core.MongoTemplate.findById(MongoTemplate.java:652)
	at org.springframework.data.mongodb.core.MongoTemplate.findById(MongoTemplate.java:645)
	at mu.cibecs.support.newton.NewtonConfiguration$1.findOneById(NewtonConfiguration.java:39)
	at io.muoncore.newton.cluster.MuonClusterAwareTrackingSubscriptionManager.getEventStreamIndex(MuonClusterAwareTrackingSubscriptionManager.java:122)
	at io.muoncore.newton.cluster.MuonClusterAwareTrackingSubscriptionManager.localTrackingSubscription(MuonClusterAwareTrackingSubscriptionManager.java:87)
	at io.muoncore.newton.cluster.MuonClusterAwareTrackingSubscriptionManager.lambda$globallyUniqueSubscription$4(MuonClusterAwareTrackingSubscriptionManager.java:67)
	at io.muoncore.newton.cluster.LocalOnlyLockService.lambda$executeAndRepeatWithLock$1(LocalOnlyLockService.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2017-07-06 08:09:08.963  INFO 25446 --- [-service/Device] i.m.newton.cluster.LocalOnlyLockService  : Global lock 'DeviceLookupService-core-service/Device' released! Will try again in 500ms
Disconnected from the target VM, address: '127.0.0.1:53933', transport: 'socket'
```

**Comment by daviddawson** [comment]
Fixed in https://github.com/muoncore/newton/commit/41450f96ff33f79c8317a3663cb4872096162eac
