### ISSUE TITLE
Less verbose 'error' logs upon lost connections

### ISSUE THREAD

**Issue by bobjana** [muoncore/newton#58]
Upon "Connection lost to remote service" which seems to be an expected condition which the client seems to recover from, it would be preferred if we could have this less verbose, if we saying this isn't a real error condition to be concerned about. 
 
```
7/13/2017 10:08:10 PM2017-07-13 20:08:10.146 INFO 10 --- [ channel-4] i.m.newton.cluster.LocalOnlyLockService : TenantPort-security-service/Customer is already unlocked
7/13/2017 10:08:10 PM2017-07-13 20:08:10.146 ERROR 10 --- [ channel-4] nClusterAwareTrackingSubscriptionManager : Error in subscription
7/13/2017 10:08:10 PM
7/13/2017 10:08:10 PMio.muoncore.exception.MuonException: Connection lost to remote service, the channel has shut down due to a transport failure
7/13/2017 10:08:10 PM at io.muoncore.protocol.reactivestream.client.ReactiveStreamClientProtocol.handleMessage(ReactiveStreamClientProtocol.java:114)
7/13/2017 10:08:10 PM at io.muoncore.channel.impl.WiretapChannel$2.lambda$send$0(WiretapChannel.java:64)
7/13/2017 10:08:10 PM at io.muoncore.transport.client.RingBufferLocalDispatcher.route(RingBufferLocalDispatcher.java:404)
7/13/2017 10:08:10 PM at io.muoncore.transport.client.RingBufferLocalDispatcher$SingleThreadTask.run(RingBufferLocalDispatcher.java:297)
7/13/2017 10:08:10 PM at io.muoncore.transport.client.RingBufferLocalDispatcher$3.onEvent(RingBufferLocalDispatcher.java:171)
7/13/2017 10:08:10 PM at io.muoncore.transport.client.RingBufferLocalDispatcher$3.onEvent(RingBufferLocalDispatcher.java:168)
7/13/2017 10:08:10 PM at reactor.jarjar.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
7/13/2017 10:08:10 PM at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
7/13/2017 10:08:10 PM at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
7/13/2017 10:08:10 PM at java.lang.Thread.run(Thread.java:745)
7/13/2017 10:08:10 PM
7/13/2017 10:08:10 PM2017-07-13 20:08:10.146 WARN 10 --- [ channel-4] nClusterAwareTrackingSubscriptionManager : NewtonEvent subscription has ended, will attempt to reconnect in 5000ms
7/13/2017 10:08:10 PM2017-07-13 20:08:10.147 INFO 10 --- [ervice/Customer] i.m.newton.cluster.LocalOnlyLockService : Global lock 'TenantPort-security-service/Customer' released! Will try again in 500ms
7/13/2017 10:08:10 PM2017-07-13 20:08:10.647 INFO 10 --- [ervice/Customer] i.m.newton.cluster.LocalOnlyLockService : Waiting on the lock TenantPort-security-service/Customer
7/13/2017 10:08:10 PM2017-07-13 20:08:10.648 INFO 10 --- [ervice/Customer] i.m.newton.cluster.LocalOnlyLockService : Obtained global lock 'TenantPort-security-service/Customer', executing local task on this node
7/13/2017 10:08:10 PM2017-07-13 20:08:10.652 INFO 10 --- [ervice/Customer] nClusterAwareTrackingSubscriptionManager : Subscribing from index 190 to event stream TenantPort-security-service/Customer 'security-service/Customer'

```

**Comment by daviddawson** [comment]
Fixed in https://github.com/muoncore/newton/commit/656c790eb006b917aeba43c4d87b0844cd34627a
